### ISSUE TITLE
Step 3 Issue

### ISSUE THREAD

**Issue by GameLord2022** [Joseph-dh-woods/IGDB-CSV-generator#1]
Hi Mate,

Some great code here i am not much of a coder i tried this and got to add Client ID and Secret and got the below errors in Colab.

Any help is appreciated i am just trying to extract the entire IGDB content so i can populate a Game Key eCommerce site

**Comment by jdhwoods** [comment]
You really shouldn't post your clientsecret on a public website like that, also you only copied the code, you didn't include any error

**Comment by jdhwoods** [comment]
Anyway this repo is not for commercial use according to the license, please remove it from your site

**Comment by GameLord2022** [comment]
I dont have it on my site as i couldnt get passed the first few steps

**Comment by GameLord2022** [comment]
Thanks anyway
